ioctl, configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,8 +4,8 @@
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Sat Jul 31 06:49:37 2004                          */
-#*    Last change :  Tue Dec 15 09:26:22 2015 (serrano)                */
-#*    Copyright   :  2004-15 Manuel Serrano                            */
+#*    Last change :  Thu Jun  2 17:12:26 2016 (serrano)                */
+#*    Copyright   :  2004-16 Manuel Serrano                            */
 #*    -------------------------------------------------------------    */
 #*    HOP autoconfiguration                                            */
 #*=====================================================================*/
@@ -34,7 +34,7 @@ javac=javac
 devmode=product
 debug=no
 
-bcflags="-O2 -fsharing -Wall -wslots -L \$(BUILDLIBDIR) -srfi bigloo-compile"
+bcflags="-O2 -fsharing -L \$(BUILDLIBDIR) -srfi bigloo-compile"
 bhflags=
 btflags="-gtrace"
 
@@ -183,6 +183,14 @@ while : ; do
     --distribdir=*)
       distribdir="`echo $1 | sed 's/^[^=]*=//'`";;
 
+    --build-bindir=*)
+      buildbindir="`echo $1 | sed 's/^[^=]*=//'`";
+      bigloo=$buildbindir/bigloo;
+      afile=$buildbindir/bglafile;
+      jfile=$buildbindir/bgljfile;
+      hop=$buildbindir/hop;
+      hopc=$buildbindir/hopc;;
+      
     --mimetypes=*)
       mimetypes="`echo $1 | sed 's/^[^=]*=//'`";;
 
@@ -192,6 +200,12 @@ while : ; do
     --cssmimetype=*)
       cssmimetype="`echo $1 | sed 's/^[^=]*=//'`";;
 
+    --hop=*)
+      hop="`echo $1 | sed 's/^[^=]*=//'`";;
+      
+    --hopc=*)
+      hopc="`echo $1 | sed 's/^[^=]*=//'`";;
+      
     --bigloo=*)
       bigloo="`echo $1 | sed 's/^[^=]*=//'`";;
 
@@ -355,6 +369,8 @@ while : ; do
       echo "*** Configure error, unknown option $1" >&2;
       echo >&2;
       echo "Usage: configure [options]" >&2;
+      echo "" >&2;
+      echo "Path:" >&2;
       echo "   --prefix=dir............... prefix to HOP install" >&2;
       echo "   --etcdir=dir............... Hop etc directory" >&2;
       echo "   --bindir=dir............... alternative Hop bin directory" >&2;
@@ -364,9 +380,13 @@ while : ; do
       echo "   --webletsdir=dir........... alternative Hop weblets directory" >&2;
       echo "   --contribsdir=dir.......... alternative Hop contribs directory" >&2;
       echo "   --docdir=dir............... alternative Hop doc directory" >&2;
+      echo "" >&2;
+      echo "Misc:" >&2;
       echo "   --mimetypes=file........... default mime.types file" >&2;
       echo "   --jsmimetype=type.......... default 'text/javascript'" >&2;
       echo "   --cssmimetype=type......... default 'text/css'" >&2;
+      echo "   --hop=comp................. The Hop binary ($hop)" >&2;
+      echo "   --hopc=comp................ The Hopc binary ($hopc)" >&2;
       echo "   --bigloo=comp.............. The Bigloo compiler ($bigloo)" >&2;
       echo "   --bigloobindir=path........ The Bigloo bin-dir path" >&2;
       echo "   --bigloolibdir=path........ The Bigloo lib-dir path" >&2;
@@ -519,20 +539,16 @@ esac
 #*    We are now able to set the correct value for cc since we know    */
 #*    what Bigloo is.                                                  */
 #*---------------------------------------------------------------------*/
-if [ "$cc " = " " ]; then
-  cc=`$bigloo -eval '(begin (print *cc*) (exit 0))'`
-fi
-
 if [ "$bigloolibdir " = " " ]; then
   bigloolibdir=`$bigloo -q -eval "(begin (print (bigloo-config 'library-directory)) (exit 0))"`
 else
   bcflags="$bcflags -lib-dir $bigloolibdir"
 fi
 
-if [ ! -f $bigloolibdir/Makefile.config ]; then
-  echo "Bigloo not properly installed, file missing:" >&2;
-  echo "  $bigloolibdir/Makefile.config" >&2;
-  exit -1;
+if [ "$cc " = " " ]; then
+  cc=`$bigloo $bcflags -eval '(begin (print *cc*) (exit 0))'`
+else  
+  bcflags="$bcflags -cc $cc"
 fi
 
 if [ "$ccflags " = " " ]; then
@@ -541,6 +557,12 @@ if [ "$ccflags " = " " ]; then
     ccflags=`echo $ccflags | sed 's/[-]O[0-9]//'`
   fi
   ccflags="$ccflags -I$bigloolibdir \$(CPICFLAGS)"
+fi
+
+if [ ! -f $bigloolibdir/Makefile.config ]; then
+  echo "Bigloo not properly installed, file missing:" >&2;
+  echo "  $bigloolibdir/Makefile.config" >&2;
+  exit -1;
 fi
 
 #*---------------------------------------------------------------------*/
@@ -788,7 +810,6 @@ if [ "$bglfail " = "true " ]; then
   exit 1
 fi    
 
-
 #*---------------------------------------------------------------------*/
 #*    Then check if bglafile exists this is a good indicator of a      */
 #*    correct Bigloo installation.                                     */
@@ -938,7 +959,19 @@ for p in hopc.sh hop.sh; do
   > bin/$p
   chmod a+rx bin/$p
 done
-    
+
+if [ "$hopc" = "$PWD/bin/hopc" ]; then
+  mkmfhopc=$hopc.sh
+else  
+  mkmfhopc=$hopc
+fi
+
+if [ "$hop" = "$PWD/bin/hop" ]; then
+  mkmfhop=$hop.sh
+else  
+  mkmfhop=$hop
+fi
+
 cat $mkmf.in \
     | sed -e "s|@RELEASE@|$version|" \
           -e "s|@BRANCH@|$branch|" \
@@ -947,8 +980,8 @@ cat $mkmf.in \
           -e "s|@DEBUG@|$debug|" \
           -e "s|@BIGLOO@|$bigloo|" \
           -e "s|@BIGLOOVERSION@|$bglversion|" \
-          -e "s|@HOP@|$hop.sh|" \
-          -e "s|@HOPC@|$hopc.sh|" \
+          -e "s|@HOP@|$mkmfhop|" \
+          -e "s|@HOPC@|$mkmfhopc|" \
           -e "s|@BGLCPP@|$bglcpp|" \
           -e "s|@BACKEND@|$backend|" \
           -e "s|@LINK@|$link|" \
@@ -1008,6 +1041,7 @@ cat $mkmf.in \
           -e "s|@BGLCLOSELIBS_S@|$bglcloselibs_s $bglextracloselibs|" \
 	  -e "s|@BGLMACH@|$mach|" \
 	  -e "s|@BGLARCH@|$arch|" \
+          -e "s|@BUILDID@|$buildid|" \
     >> $mkmf
 
 # runtime/configure.scm
@@ -1040,6 +1074,7 @@ for p in configure.scm configure_noarch.sch configure_macosx.sch configure_andro
             -e "s|@HOPSRFIS@|$hopsrfis|" \
             -e "s|@HOPMACH@|$mach|" \
             -e "s|@HOPARCH@|$arch|" \
+            -e "s|@BUILDID@|$buildid|" \
       >> $configure
 done
 
@@ -1367,6 +1402,7 @@ for init in hop-autoconf.js hop-boot.js; do
             -e "s|@WEBLETSDIR@|$webletsdir|" \
             -e "s|@LOCEVENT@|$locevent|" \
             -e "s|@HOPSERVICEBASE@|$hopservicebase|" \
+            -e "s|@BUILD@|$builid|" \
             -e "s|//[^\"]*$$||g" \
             -e "/^[ \t]*$$/D" \
       >> share/$init
@@ -1476,4 +1512,9 @@ echo "  runtime compilation flags............. $bcflagsrts"
 echo "  mime types............................ $mimetypes"
 echo "  default JavaScript mime type.......... $jsmimetype"
 echo "  default CSS mime type................. $cssmimetype"
+echo "  closure compiler (optional)........... $closure"
+echo
+echo "Bootstrap compilers:"
+echo "  hop................................... $hop"
+echo "  hopc.................................. $hopc"
 
