Improve the auto-configuration.
The configure script now checks that Bigloo is correctly installed with
the support for the pthread and multimedia.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Sat Jul 31 06:49:37 2004                          */
-#*    Last change :  Mon Jul 24 08:28:17 2006 (serrano)                */
+#*    Last change :  Wed Aug 23 15:04:23 2006 (serrano)                */
 #*    Copyright   :  2004-06 Manuel Serrano                            */
 #*    -------------------------------------------------------------    */
 #*    HOP autoconfiguration                                            */
@@ -56,7 +56,7 @@ buildbindir=$PWD/bin
 
 repository=$HOME/prgm/project/hop/devel/repository
 
-bigloorequired=2.8a
+bigloorequired=2.8c
 bigloourl=http://www.inria.fr/mimosa/fp/Bigloo
 
 svn=ssh://hop@hop.inria.fr/hop
@@ -206,6 +206,30 @@ if [ $? != "0" ]; then
   echo "   $bigloourl"
   exit 1;
 fi
+
+#*---------------------------------------------------------------------*/
+#*    Check the Bigloo libraries                                       */
+#*---------------------------------------------------------------------*/
+bgllibdir=`$bigloo -q -eval "(begin (print *ld-library-dir*) (exit 0))"`
+
+if [ ! -f $bgllibdir/$bglversion/pthread.heap ]; then
+  echo "*** ERROR:configure:bigloo pthread. Aborting"
+  echo ""
+  echo "This error is due to a bad Bigloo installation. It might be that"
+  echo "you have installed Bigloo without the pthread support. Please"
+  echo "check your Bigloo installation."
+  exit 1;
+fi
+
+if [ ! -f $bgllibdir/$bglversion/multimedia.heap ]; then
+  echo "*** ERROR:configure:bigloo pthread. Aborting"
+  echo ""
+  echo "This error is due to a bad Bigloo installation. It might be that"
+  echo "you have installed Bigloo without the multimedia support. Please"
+  echo "check your Bigloo installation."
+  exit 1;
+fi
+
 
 #*---------------------------------------------------------------------*/
 #*    Then check if bglafile exists this is a good indicator of a      */
